---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole-certificate
  namespace: pihole
spec:
  secretName: pihole-local-icutum-es-tls
  issuerRef:
    name: cert-manager-cluster-issuer
    kind: ClusterIssuer
  commonName: "pihole.local.icutum.es"
  dnsNames:
    - "pihole.local.icutum.es"
