---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole-ingress
  namespace: pihole
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pihole.local.icutum.es`)
      kind: Rule
      services:
        - name: pihole-service-frontend
          port: 31415
  tls:
    secretName: pihole-local-icutum-es-tls
