---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-prometheus-stack-grafana-ingress
  namespace: kube-prometheus-stack
  annotations:
    external-dns.alpha.kubernetes.io/hostname: grafana.local.icutum.es
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
    - host: grafana.local.icutum.es
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-stack-helmrelease-grafana
                port:
                  number: 80
  tls:
    - hosts:
        - grafana.local.icutum.es
      secretName: grafana-local-icutum-es-tls
