---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack-helmrelease
  namespace: kube-prometheus-stack
spec:
  interval: 10m0s
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 81.5.0
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack-helmrepository
        namespace: flux-system
  values:
    cleanPrometheusOperatorObjectNames: true
    kubeEtcd:
      endpoints:
        - 192.168.1.3
        - 192.168.1.4
        - 192.168.1.5
    kubelet:
      jobNameOverride: "k3s-server"
    kubeControllerManager:
      jobNameOverride: "k3s-server"
    kubeScheduler:
      jobNameOverride: "k3s-server"
    kubeProxy:
      jobNameOverride: "k3s-server"
    grafana:
      dashboards:
        default:
          flux-cluster:
            url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/refs/heads/main/monitoring/configs/dashboards/cluster.json
            datasource: Prometheus
          flux-control-plane:
            url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/refs/heads/main/monitoring/configs/dashboards/control-plane.json
            datasource: Prometheus
