---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kube-prometheus-stack-helmrepository
  namespace: flux-system
spec:
  type: oci
  interval: 10m0s
  url: oci://ghcr.io/prometheus-community/charts
