---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-certificate
  namespace: traefik
spec:
  secretName: traefik-local-icutum-es-tls
  issuerRef:
    name: cert-manager-cluster-issuer
    kind: ClusterIssuer
  commonName: "traefik.local.icutum.es"
  dnsNames:
    - "traefik.local.icutum.es"
