---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-ingress-dashboard
  namespace: traefik
  annotations:
    external-dns.alpha.kubernetes.io/hostname: traefik.local.icutum.es
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-traefik-dashboard-basicauth@kubernetescrd
spec:
  rules:
    - host: traefik.local.icutum.es
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traefik
                port:
                  number: 8080
  tls:
    - hosts:
        - traefik.local.icutum.es
      secretName: traefik-local-icutum-es-tls
