---
apiVersion: v1
kind: Secret
metadata:
    name: traefik-dashboard-auth
    namespace: traefik
type: Opaque
data:
    users: ENC[AES256_GCM,data:L3urXD4pNG0keKy6xKronIrMyvWFUfejPhxT4Pz9DaaYTB7RZ6nPOxytSlfTMs5cGKt2EbRam135rPst,iv:afGkK8+h8HsNPyoC6KWDICp3iSmtsBMdKqQq155CqIc=,tag:jnqRM25JpmfUD9lu1Id97g==,type:str]
sops:
    age:
        - recipient: age14e9960ys3tqpnr40memrdp8uac0f86wv326ykwkwrufgrv4a5dtsd58zd2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOHVtQXRYM09hM25DWWtj
            S1RCZFdyTk1KTi9oUVhqdFRtbzNaT2ZrNHh3Cms0V0czNFU1VkozR2VKNVNDandw
            UGJJbXpjOUJmb0dUcVJ5ZUFHUU9nVzAKLS0tIHlpWEJlYjVaQnhFSTRtKzI3VEdQ
            SW9ick0zenkrem9qMzhzanlBSng2bHMKI+zURVTCUy/3F8fi8d7ikw9k032zwjrw
            /UHYfWYitx6kNYGKfKtjrZq7Vc1WwiX6MQS1oOxQJbMqD3AT3WCbxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T20:10:54Z"
    mac: ENC[AES256_GCM,data:He1osgnKcMwbbQKb1tqacKh8V6RCkGl1D1a3kORvwf1JRItuARQWSDmDBqFZ8oLweegHz8TpjT4opS2F4GBBqM01sPKsdkcjn957uI4hSnGFA/+AnH0p/4Y6a9mShYZxRx2J+ncegxgJj646lMeaKdd5TuoYrtcJg4PQpU7A7ys=,iv:vkW9Ovaag0k5mix+O/WP9ce+OgyNLNjfrX3sR9ts76E=,tag:Hd2so6/j5VVZ9qnp7ObgSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
