---
apiVersion: v1
kind: Service
metadata:
  name: pihole-service-frontend
  namespace: pihole
spec:
  ports:
    - name: http
      protocol: TCP
      port: 31415
      targetPort: 31415
  clusterIP: None
