---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-dns-proxmox-certificate
  namespace: external-dns
spec:
  secretName: proxmox-local-icutum-es-tls
  issuerRef:
    name: cert-manager-cluster-issuer
    kind: ClusterIssuer
  commonName: "proxmox.local.icutum.es"
  dnsNames:
    - "proxmox.local.icutum.es"
