---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-system-ipaddresspool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.100-192.168.1.100
  autoAssign: false
