---
apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-cloudflare-token
    namespace: cert-manager
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:zJbPD0dEVVWHlnS/CKDVtHUXZuubyuvpQDO/pTcFCzxUwugcBJd/MQ==,iv:7cfn7hbuoHnKo/1w86tvaWV0E8Mt857P8shvDEaLchU=,tag:Uq4IgydbWaWIZ6G7CFuTPQ==,type:str]
sops:
    age:
        - recipient: age14e9960ys3tqpnr40memrdp8uac0f86wv326ykwkwrufgrv4a5dtsd58zd2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqL3lBQUphQ2hmN05VL0FX
            ckNNVTlnYzIwd0hkQ0ZnbENFdmQyS0RrSVRBCjRMcWJIOXZJQ3NkYzdpUUFmd3gy
            ZTJNNURFL0ZyRXlQZ3Z0K1ZyRGhHQW8KLS0tICsvVWFDMTM5UVFaUjE3M1lmK25S
            Ym16NVU1S1MvbFRVMDBZZjlGWUgveGcKU8mXCzYeE28NfvIWY6M9jeJtUVhXfw1M
            O+JmNa44oUWmjHMNOnVjsoAdYL+/cgWZjT3yiJcprhaGguAnijNekA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T21:46:03Z"
    mac: ENC[AES256_GCM,data:B/354Ls2mtcbVWc5R/Gl2xu2GlSpNDn/T5NryQ8j+PtWMPZYJFg3VHoiWgyA03BQsxbITtaBDMPDAVn7SS9CHtz6b3XwHZ/RxIIEqRPChRZ7eTrzkGaR0Wj4iTQBdDdpz1DbgzCNmAsH6VkHcZwbdDrb0mh7nFUp5PTBrlJEYsE=,iv:L5We8VPEUTnNPd7s0r0IPb4lPbOruZy21Kn93eCHWFI=,tag:z3jUZ82mc5OG+pB5/A38ag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
